# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       openrepos-tsumego

# >> macros
# << macros

Summary:    go problem game
Version:    0.3.1
Release:    2
Group:      Amusements/Games
License:    unknown
BuildArch:  noarch
URL:        http://openrepos.net/nephros/openrepos-tsumego
Source0:    %{name}-%{version}.tar.gz
Source100:  openrepos-tsumego.yaml
Requires:   python
Requires:   pyotherside-qml-plugin-python3-qt5
Requires:   sailfishsilica-qt5
Requires:   libsailfishapp-launcher
BuildRequires:  desktop-file-utils
Obsoletes:   tsumego = 0.1-1
Obsoletes:   openrepos-tsumego <= 0.2

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
#install -D -p -m 755 %%{name} %%{buildroot}/%%{_bindir}/%%{name}
install -D -p -m 644 %{name}.desktop %{buildroot}/%{_datadir}/applications/%{name}.desktop
for f in $(find qml translations -type f | grep -v \\.swp); do
install -D -p -m 644 ${f} %{buildroot}/%{_datadir}/%{name}/${f}
done
mkdir -p %{buildroot}/%{_datadir}/icons/hicolor/86x86/apps/
cp -r %{name}.png %{buildroot}/%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/%{name}/qml/*
%{_datadir}/%{name}/translations/*.qm
# >> files
# << files
